# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ErrorState(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, error_code: str=None, error_message: str=None):
        """
        ErrorState - a model defined in Swagger

        :param error_code: The error_code of this ErrorState.
        :type error_code: str
        :param error_message: The error_message of this ErrorState.
        :type error_message: str
        """
        self.swagger_types = {
            'error_code': str,
            'error_message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'error_message': 'errorMessage'
        }

        self._error_code = error_code
        self._error_message = error_message

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorState':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorState of this ErrorState.
        :rtype: ErrorState
        """
        return deserialize_model(dikt, cls)

    @property
    def error_code(self) -> str:
        """
        Gets the error_code of this ErrorState.
        Error Code of error message

        :return: The error_code of this ErrorState.
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: str):
        """
        Sets the error_code of this ErrorState.
        Error Code of error message

        :param error_code: The error_code of this ErrorState.
        :type error_code: str
        """

        self._error_code = error_code

    @property
    def error_message(self) -> str:
        """
        Gets the error_message of this ErrorState.
        Textual error message

        :return: The error_message of this ErrorState.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """
        Sets the error_message of this ErrorState.
        Textual error message

        :param error_message: The error_message of this ErrorState.
        :type error_message: str
        """

        self._error_message = error_message

