# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class LightState(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, lux: float=None):
        """
        LightState - a model defined in Swagger

        :param lux: The lux of this LightState.
        :type lux: float
        """
        self.swagger_types = {
            'lux': float
        }

        self.attribute_map = {
            'lux': 'lux'
        }

        self._lux = lux

    @classmethod
    def from_dict(cls, dikt) -> 'LightState':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LightState of this LightState.
        :rtype: LightState
        """
        return deserialize_model(dikt, cls)

    @property
    def lux(self) -> float:
        """
        Gets the lux of this LightState.
        Current illumination of Garage in LUX

        :return: The lux of this LightState.
        :rtype: float
        """
        return self._lux

    @lux.setter
    def lux(self, lux: float):
        """
        Sets the lux of this LightState.
        Current illumination of Garage in LUX

        :param lux: The lux of this LightState.
        :type lux: float
        """

        self._lux = lux

